# Generated by Django 5.1.6 on 2025-02-17 14:16
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("shirt_number", models.IntegerField(default=0)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("goalkeeper", "GOALKEEPER"),
                            ("defender", "DEFENDER"),
                            ("midfielder", "MIDFIELDER"),
                            ("forward", "FORWARD"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "image_url",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("mvps", models.IntegerField(default=0)),
                ("yellow_cards", models.IntegerField(default=0)),
                ("red_cards", models.IntegerField(default=0)),
            ],
        ),
    ]
