# Generated by Django 5.1.6 on 2025-02-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("players", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="player",
            table="player",
        ),
    ]
